// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applink-version.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "ApplinkVersion.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - serviceapplinkApplinkVersionRoot

@implementation serviceapplinkApplinkVersionRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum serviceapplinkClientType

GPBEnumDescriptor *serviceapplinkClientType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "ClientTypeAndroid\000ClientTypeIos\000ClientTy"
        "peIosSign\000ClientTypeIosTf\000";
    static const int32_t values[] = {
        serviceapplinkClientType_ClientTypeAndroid,
        serviceapplinkClientType_ClientTypeIos,
        serviceapplinkClientType_ClientTypeIosSign,
        serviceapplinkClientType_ClientTypeIosTf,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(serviceapplinkClientType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:serviceapplinkClientType_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      
    }
  }
  return descriptor;
}

BOOL serviceapplinkClientType_IsValidValue(int32_t value__) {
  switch (value__) {
    case serviceapplinkClientType_ClientTypeAndroid:
    case serviceapplinkClientType_ClientTypeIos:
    case serviceapplinkClientType_ClientTypeIosSign:
    case serviceapplinkClientType_ClientTypeIosTf:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
