// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-content.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiContentTag;
@class appvapiIdEncode;
@class appvapiMIMEInfo;
@class appvapiShareCode;
@class appvapiUserInfoBasic;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - appvapiAppvPrimaryContentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryContentRoot : GPBRootObject
@end

#pragma mark - appvapiContentSvideo

typedef GPB_ENUM(appvapiContentSvideo_FieldNumber) {
  appvapiContentSvideo_FieldNumber_SvideoId = 1,
  appvapiContentSvideo_FieldNumber_Title = 2,
  appvapiContentSvideo_FieldNumber_CoverURL = 3,
  appvapiContentSvideo_FieldNumber_VideoURL = 4,
  appvapiContentSvideo_FieldNumber_TagsArray = 5,
  appvapiContentSvideo_FieldNumber_Likes = 6,
  appvapiContentSvideo_FieldNumber_IsLike = 7,
  appvapiContentSvideo_FieldNumber_IsCollection = 8,
  appvapiContentSvideo_FieldNumber_UserInfo = 9,
  appvapiContentSvideo_FieldNumber_Comments = 10,
  appvapiContentSvideo_FieldNumber_Shares = 11,
  appvapiContentSvideo_FieldNumber_CreateAt = 12,
  appvapiContentSvideo_FieldNumber_ShareCode = 13,
  appvapiContentSvideo_FieldNumber_FirstFrameFile = 14,
};

/**
 * 只要拿到此结构 客户端可以直接打开播放页
 **/
GPB_FINAL @interface appvapiContentSvideo : GPBMessage

/** 内容ID */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *svideoId;
/** Test to see if @c svideoId has been set. */
@property(nonatomic, readwrite) BOOL hasSvideoId;

/** 内容标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 封面 url */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *coverURL;
/** Test to see if @c coverURL has been set. */
@property(nonatomic, readwrite) BOOL hasCoverURL;

/** 资源 url */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *videoURL;
/** Test to see if @c videoURL has been set. */
@property(nonatomic, readwrite) BOOL hasVideoURL;

/** 视频 tag */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiContentTag*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

/** 视频点赞数 */
@property(nonatomic, readwrite) uint64_t likes;

/** 我是否点赞过该视频 */
@property(nonatomic, readwrite) BOOL isLike;

/** 是否收藏了此视频 */
@property(nonatomic, readwrite) BOOL isCollection;

/** 视频作者信息用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiUserInfoBasic *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

/** 评论总数 */
@property(nonatomic, readwrite) uint64_t comments;

/** 分享总数 */
@property(nonatomic, readwrite) uint64_t shares;

/** 创建时间 */
@property(nonatomic, readwrite) uint64_t createAt;

/** 分享码 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiShareCode *shareCode;
/** Test to see if @c shareCode has been set. */
@property(nonatomic, readwrite) BOOL hasShareCode;

/** 第一帧图片 文件名及拓展类型 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *firstFrameFile;
/** Test to see if @c firstFrameFile has been set. */
@property(nonatomic, readwrite) BOOL hasFirstFrameFile;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
