// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-community.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiContentTag;
@class appvapiIdEncode;
@class appvapiMIMEInfo;
@class appvapiUserInfoBasic;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum appvapiCommunityPostResourceType

typedef GPB_ENUM(appvapiCommunityPostResourceType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  appvapiCommunityPostResourceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 无资源 */
  appvapiCommunityPostResourceType_CommunityPostResourceTypeUnspecified = 0,

  /** 图片 */
  appvapiCommunityPostResourceType_CommunityPostResourceTypePicture = 1,

  /** 视频 */
  appvapiCommunityPostResourceType_CommunityPostResourceTypeVideo = 2,
};

GPBEnumDescriptor *appvapiCommunityPostResourceType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL appvapiCommunityPostResourceType_IsValidValue(int32_t value);

#pragma mark - Enum appvapiContentCommunityPostStatus

typedef GPB_ENUM(appvapiContentCommunityPostStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  appvapiContentCommunityPostStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  appvapiContentCommunityPostStatus_ContentCommunityPostStatusUnspecified = 0,

  /** 待审核 */
  appvapiContentCommunityPostStatus_ContentCommunityPostStatusAuditing = 1,

  /** 审核拒绝 */
  appvapiContentCommunityPostStatus_ContentCommunityPostStatusAuditDeny = 2,

  /** 审核通过 */
  appvapiContentCommunityPostStatus_ContentCommunityPostStatusAuditPass = 3,
};

GPBEnumDescriptor *appvapiContentCommunityPostStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL appvapiContentCommunityPostStatus_IsValidValue(int32_t value);

#pragma mark - appvapiAppvPrimaryCommunityRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryCommunityRoot : GPBRootObject
@end

#pragma mark - appvapiCommunityPost

typedef GPB_ENUM(appvapiCommunityPost_FieldNumber) {
  appvapiCommunityPost_FieldNumber_Id_p = 1,
  appvapiCommunityPost_FieldNumber_UserInfoBasic = 2,
  appvapiCommunityPost_FieldNumber_Content = 3,
  appvapiCommunityPost_FieldNumber_CommunityPostResourceType = 4,
  appvapiCommunityPost_FieldNumber_ResourcesArray = 5,
  appvapiCommunityPost_FieldNumber_StarNumber = 6,
  appvapiCommunityPost_FieldNumber_CommentNumber = 7,
  appvapiCommunityPost_FieldNumber_CollectNumber = 8,
  appvapiCommunityPost_FieldNumber_CreateAt = 9,
  appvapiCommunityPost_FieldNumber_ContentCommunityPostStatus = 10,
  appvapiCommunityPost_FieldNumber_TagsArray = 11,
  appvapiCommunityPost_FieldNumber_IsLike = 12,
  appvapiCommunityPost_FieldNumber_IsCollection = 13,
  appvapiCommunityPost_FieldNumber_CoverURL = 14,
  appvapiCommunityPost_FieldNumber_AuditReason = 15,
  appvapiCommunityPost_FieldNumber_IsFollow = 16,
  appvapiCommunityPost_FieldNumber_IsTop = 17,
  appvapiCommunityPost_FieldNumber_PictureThumbnailsArray = 18,
};

GPB_FINAL @interface appvapiCommunityPost : GPBMessage

/** 帖子id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

/** 帖子用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiUserInfoBasic *userInfoBasic;
/** Test to see if @c userInfoBasic has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfoBasic;

/** 帖子文本内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 帖子资源类型 */
@property(nonatomic, readwrite) appvapiCommunityPostResourceType communityPostResourceType;

/** 帖子资源集合(源文件) */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiMIMEInfo*> *resourcesArray;
/** The number of items in @c resourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resourcesArray_Count;

/** 点赞数 */
@property(nonatomic, readwrite) uint64_t starNumber;

/** 评论数 */
@property(nonatomic, readwrite) uint64_t commentNumber;

/** 收藏数 */
@property(nonatomic, readwrite) uint64_t collectNumber;

/** 发布时间 */
@property(nonatomic, readwrite) uint64_t createAt;

/** 审核状态 */
@property(nonatomic, readwrite) appvapiContentCommunityPostStatus contentCommunityPostStatus;

/** 帖子 tag */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiContentTag*> *tagsArray;
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

/** 我是否点赞过该视频 */
@property(nonatomic, readwrite) BOOL isLike;

/** 是否收藏了此视频 */
@property(nonatomic, readwrite) BOOL isCollection;

/** 视频帖子的封面url */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *coverURL;
/** Test to see if @c coverURL has been set. */
@property(nonatomic, readwrite) BOOL hasCoverURL;

/** 审核原因 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *auditReason;

/** 是否关注 */
@property(nonatomic, readwrite) BOOL isFollow;

/** 是否置顶 */
@property(nonatomic, readwrite) BOOL isTop;

/** 图片缩略图集合 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiMIMEInfo*> *pictureThumbnailsArray;
/** The number of items in @c pictureThumbnailsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pictureThumbnailsArray_Count;

@end

/**
 * Fetches the raw value of a @c appvapiCommunityPost's @c communityPostResourceType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t appvapiCommunityPost_CommunityPostResourceType_RawValue(appvapiCommunityPost *message);
/**
 * Sets the raw value of an @c appvapiCommunityPost's @c communityPostResourceType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetappvapiCommunityPost_CommunityPostResourceType_RawValue(appvapiCommunityPost *message, int32_t value);

/**
 * Fetches the raw value of a @c appvapiCommunityPost's @c contentCommunityPostStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t appvapiCommunityPost_ContentCommunityPostStatus_RawValue(appvapiCommunityPost *message);
/**
 * Sets the raw value of an @c appvapiCommunityPost's @c contentCommunityPostStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetappvapiCommunityPost_ContentCommunityPostStatus_RawValue(appvapiCommunityPost *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
