// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-api-oss.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiCallbackEvent;
@class appvapiIdEncode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum appvapiCallbackEvent_Status

typedef GPB_ENUM(appvapiCallbackEvent_Status) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  appvapiCallbackEvent_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  appvapiCallbackEvent_Status_StatusUnspecified = 0,

  /** 上传成功 */
  appvapiCallbackEvent_Status_StatusSuccess = 1,

  /** 上传取消 */
  appvapiCallbackEvent_Status_StatusCancel = 2,

  /** 上传失败，网络异常 */
  appvapiCallbackEvent_Status_StatusNetworkError = 3,

  /** 上传失败，crc错误 */
  appvapiCallbackEvent_Status_StatusCrcError = 4,
};

GPBEnumDescriptor *appvapiCallbackEvent_Status_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL appvapiCallbackEvent_Status_IsValidValue(int32_t value);

#pragma mark - appvapiAppvPrimaryApiOssRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryApiOssRoot : GPBRootObject
@end

#pragma mark - appvapiCallbackMessageReq

typedef GPB_ENUM(appvapiCallbackMessageReq_FieldNumber) {
  appvapiCallbackMessageReq_FieldNumber_BatchId = 1,
  appvapiCallbackMessageReq_FieldNumber_Event = 2,
};

/**
 * 客户端上传回调后请求服务端的参数
 **/
GPB_FINAL @interface appvapiCallbackMessageReq : GPBMessage

/** 上传行为的批次id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *batchId;
/** Test to see if @c batchId has been set. */
@property(nonatomic, readwrite) BOOL hasBatchId;

/** 上传行为的任务信息 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiCallbackEvent *event;
/** Test to see if @c event has been set. */
@property(nonatomic, readwrite) BOOL hasEvent;

@end

#pragma mark - appvapiCallbackEvent

typedef GPB_ENUM(appvapiCallbackEvent_FieldNumber) {
  appvapiCallbackEvent_FieldNumber_EventId = 1,
  appvapiCallbackEvent_FieldNumber_Status = 2,
  appvapiCallbackEvent_FieldNumber_DeviceInfo = 3,
};

/**
 * 上传行为的任务信息
 **/
GPB_FINAL @interface appvapiCallbackEvent : GPBMessage

/** 上传资源任务id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *eventId;
/** Test to see if @c eventId has been set. */
@property(nonatomic, readwrite) BOOL hasEventId;

/** 上传资源任务的结果 */
@property(nonatomic, readwrite) appvapiCallbackEvent_Status status;

/** 设备信息 Android IOS */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceInfo;

@end

/**
 * Fetches the raw value of a @c appvapiCallbackEvent's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t appvapiCallbackEvent_Status_RawValue(appvapiCallbackEvent *message);
/**
 * Sets the raw value of an @c appvapiCallbackEvent's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetappvapiCallbackEvent_Status_RawValue(appvapiCallbackEvent *message, int32_t value);

#pragma mark - appvapiUploadCallbackResp

typedef GPB_ENUM(appvapiUploadCallbackResp_FieldNumber) {
  appvapiUploadCallbackResp_FieldNumber_Success = 1,
};

/**
 * 客户端上传回调后服务端的响应结果
 **/
GPB_FINAL @interface appvapiUploadCallbackResp : GPBMessage

/** 服务端是否收到数据 */
@property(nonatomic, readwrite) BOOL success;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
