// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-customer.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "AppvCustomer.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - appvapiAppvCustomerRoot

@implementation appvapiAppvCustomerRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum appvapiWorkOrderStatus

GPBEnumDescriptor *appvapiWorkOrderStatus_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Create\000Pending\000Replied\000Resolved\000";
    static const int32_t values[] = {
        appvapiWorkOrderStatus_Create,
        appvapiWorkOrderStatus_Pending,
        appvapiWorkOrderStatus_Replied,
        appvapiWorkOrderStatus_Resolved,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(appvapiWorkOrderStatus)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:appvapiWorkOrderStatus_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      
    }
  }
  return descriptor;
}

BOOL appvapiWorkOrderStatus_IsValidValue(int32_t value__) {
  switch (value__) {
    case appvapiWorkOrderStatus_Create:
    case appvapiWorkOrderStatus_Pending:
    case appvapiWorkOrderStatus_Replied:
    case appvapiWorkOrderStatus_Resolved:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
