// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-basic.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiCommunityPostPicture;
@class appvapiMIMEInfo;
@class appvapiPublishingCommunityPostPicture;
@class appvapiPublishingCommunityPostVideo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum appvapiGenders

typedef GPB_ENUM(appvapiGenders) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  appvapiGenders_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  appvapiGenders_None = 0,
  appvapiGenders_Nosex = 1,
  appvapiGenders_Male = 2,
  appvapiGenders_Female = 3,
};

GPBEnumDescriptor *appvapiGenders_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL appvapiGenders_IsValidValue(int32_t value);

#pragma mark - appvapiAppvBasicRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvBasicRoot : GPBRootObject
@end

#pragma mark - appvapiEmptyRequest

/**
 * 空 request
 **/
GPB_FINAL @interface appvapiEmptyRequest : GPBMessage

@end

#pragma mark - appvapiEmptyResponse

GPB_FINAL @interface appvapiEmptyResponse : GPBMessage

@end

#pragma mark - appvapiGender

typedef GPB_ENUM(appvapiGender_FieldNumber) {
  appvapiGender_FieldNumber_Gender = 1,
};

GPB_FINAL @interface appvapiGender : GPBMessage

@property(nonatomic, readwrite) appvapiGenders gender;

@end

/**
 * Fetches the raw value of a @c appvapiGender's @c gender property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t appvapiGender_Gender_RawValue(appvapiGender *message);
/**
 * Sets the raw value of an @c appvapiGender's @c gender property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetappvapiGender_Gender_RawValue(appvapiGender *message, int32_t value);

#pragma mark - appvapiIdEncode

typedef GPB_ENUM(appvapiIdEncode_FieldNumber) {
  appvapiIdEncode_FieldNumber_Id_p = 1,
};

/**
 * 对于 code id 进行了一次 编码解码
 * 与 v.basic.IdUint64
 **/
GPB_FINAL @interface appvapiIdEncode : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - appvapiAppendIdEncode

typedef GPB_ENUM(appvapiAppendIdEncode_FieldNumber) {
  appvapiAppendIdEncode_FieldNumber_LastId = 1,
};

/**
 * 与 Appendv.basic.IdUint64 一样
 * encodeId
 **/
GPB_FINAL @interface appvapiAppendIdEncode : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastId;

@end

#pragma mark - appvapiMIMEInfo

typedef GPB_ENUM(appvapiMIMEInfo_FieldNumber) {
  appvapiMIMEInfo_FieldNumber_URL = 1,
  appvapiMIMEInfo_FieldNumber_FileByteSize = 2,
  appvapiMIMEInfo_FieldNumber_AspectRatio = 3,
  appvapiMIMEInfo_FieldNumber_Extra = 4,
};

GPB_FINAL @interface appvapiMIMEInfo : GPBMessage

/** 媒体文件地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 文件大小 */
@property(nonatomic, readwrite) uint64_t fileByteSize;

/** 媒体宽高比 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *aspectRatio;

/** 拓展信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@end

#pragma mark - appvapiShareCode

typedef GPB_ENUM(appvapiShareCode_FieldNumber) {
  appvapiShareCode_FieldNumber_ShareCode = 1,
  appvapiShareCode_FieldNumber_Args = 2,
};

/**
 * 分享码
 * 生成分享链接 hots + args
 **/
GPB_FINAL @interface appvapiShareCode : GPBMessage

/** 分享码 用于页面展示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shareCode;

/** 参数 参数签名后的 用于拼接分享链接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *args;

@end

#pragma mark - appvapiPublishingCommunityPostMedia

typedef GPB_ENUM(appvapiPublishingCommunityPostMedia_FieldNumber) {
  appvapiPublishingCommunityPostMedia_FieldNumber_PublishingCommunityPostVideo = 1,
  appvapiPublishingCommunityPostMedia_FieldNumber_PublishingCommunityPostPicture = 2,
};

/**
 * 帖子资源封装
 **/
GPB_FINAL @interface appvapiPublishingCommunityPostMedia : GPBMessage

/** 帖子视频资源 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiPublishingCommunityPostVideo *publishingCommunityPostVideo;
/** Test to see if @c publishingCommunityPostVideo has been set. */
@property(nonatomic, readwrite) BOOL hasPublishingCommunityPostVideo;

/** 帖子图片资源 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiPublishingCommunityPostPicture *publishingCommunityPostPicture;
/** Test to see if @c publishingCommunityPostPicture has been set. */
@property(nonatomic, readwrite) BOOL hasPublishingCommunityPostPicture;

@end

#pragma mark - appvapiPublishingCommunityPostVideo

typedef GPB_ENUM(appvapiPublishingCommunityPostVideo_FieldNumber) {
  appvapiPublishingCommunityPostVideo_FieldNumber_Resources = 1,
  appvapiPublishingCommunityPostVideo_FieldNumber_CoverFile = 2,
};

GPB_FINAL @interface appvapiPublishingCommunityPostVideo : GPBMessage

/** 帖子视频资源 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *resources;
/** Test to see if @c resources has been set. */
@property(nonatomic, readwrite) BOOL hasResources;

/** 封面 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *coverFile;
/** Test to see if @c coverFile has been set. */
@property(nonatomic, readwrite) BOOL hasCoverFile;

@end

#pragma mark - appvapiPublishingCommunityPostPicture

typedef GPB_ENUM(appvapiPublishingCommunityPostPicture_FieldNumber) {
  appvapiPublishingCommunityPostPicture_FieldNumber_ResourcesArray = 1,
};

GPB_FINAL @interface appvapiPublishingCommunityPostPicture : GPBMessage

/** 帖子图片资源集合 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiCommunityPostPicture*> *resourcesArray;
/** The number of items in @c resourcesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resourcesArray_Count;

@end

#pragma mark - appvapiCommunityPostPicture

typedef GPB_ENUM(appvapiCommunityPostPicture_FieldNumber) {
  appvapiCommunityPostPicture_FieldNumber_Picture = 1,
  appvapiCommunityPostPicture_FieldNumber_PictureThumbnail = 2,
};

GPB_FINAL @interface appvapiCommunityPostPicture : GPBMessage

/** 帖子图片 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *picture;
/** Test to see if @c picture has been set. */
@property(nonatomic, readwrite) BOOL hasPicture;

/** 帖子缩略图 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiMIMEInfo *pictureThumbnail;
/** Test to see if @c pictureThumbnail has been set. */
@property(nonatomic, readwrite) BOOL hasPictureThumbnail;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
