// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-api-visitor.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiCommunityPost;
@class appvapiContentSvideoAppendList;
@class appvapiIdEncode;
@class appvapiUserInfoBasic;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - appvapiAppvPrimaryApiVisitorRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryApiVisitorRoot : GPBRootObject
@end

#pragma mark - appvapiListOthersShortVideoRequest

typedef GPB_ENUM(appvapiListOthersShortVideoRequest_FieldNumber) {
  appvapiListOthersShortVideoRequest_FieldNumber_LastId = 1,
  appvapiListOthersShortVideoRequest_FieldNumber_Uid = 2,
};

GPB_FINAL @interface appvapiListOthersShortVideoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastId;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@end

#pragma mark - appvapiVisitUserInfoResponse

typedef GPB_ENUM(appvapiVisitUserInfoResponse_FieldNumber) {
  appvapiVisitUserInfoResponse_FieldNumber_Info = 1,
  appvapiVisitUserInfoResponse_FieldNumber_SvideoList = 2,
};

/**
 * 访客用户响应 body
 **/
GPB_FINAL @interface appvapiVisitUserInfoResponse : GPBMessage

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiUserInfoBasic *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

/** 用户第一页的视频列表 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiContentSvideoAppendList *svideoList;
/** Test to see if @c svideoList has been set. */
@property(nonatomic, readwrite) BOOL hasSvideoList;

@end

#pragma mark - appvapiListUserCommunityPostsRequest

typedef GPB_ENUM(appvapiListUserCommunityPostsRequest_FieldNumber) {
  appvapiListUserCommunityPostsRequest_FieldNumber_Uid = 1,
  appvapiListUserCommunityPostsRequest_FieldNumber_LastId = 2,
};

GPB_FINAL @interface appvapiListUserCommunityPostsRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *lastId;
/** Test to see if @c lastId has been set. */
@property(nonatomic, readwrite) BOOL hasLastId;

@end

#pragma mark - appvapiListUserCommunityPostsResponse

typedef GPB_ENUM(appvapiListUserCommunityPostsResponse_FieldNumber) {
  appvapiListUserCommunityPostsResponse_FieldNumber_Info = 1,
  appvapiListUserCommunityPostsResponse_FieldNumber_CommunityPostsArray = 2,
};

GPB_FINAL @interface appvapiListUserCommunityPostsResponse : GPBMessage

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiUserInfoBasic *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiCommunityPost*> *communityPostsArray;
/** The number of items in @c communityPostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger communityPostsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
