// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-api-recommend.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiBrowseOtherHomepage;
@class appvapiClickPostTag;
@class appvapiClickVideoTag;
@class appvapiCollectVideo;
@class appvapiCommunityPost;
@class appvapiIdEncode;
@class appvapiLikeVideo;
@class appvapiPlayVideo;
@class appvapiPlayVideoFulfill;
@class appvapiVisitHomepageForPost;
@class appvapiVisitHomepageForVideo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - appvapiAppvPrimaryApiRecommendRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryApiRecommendRoot : GPBRootObject
@end

#pragma mark - appvapiListRecommendCommunityPostsResponse

typedef GPB_ENUM(appvapiListRecommendCommunityPostsResponse_FieldNumber) {
  appvapiListRecommendCommunityPostsResponse_FieldNumber_CommunityPostArray = 1,
};

GPB_FINAL @interface appvapiListRecommendCommunityPostsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiCommunityPost*> *communityPostArray;
/** The number of items in @c communityPostArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger communityPostArray_Count;

@end

#pragma mark - appvapiCollectRequest

typedef GPB_ENUM(appvapiCollectRequest_FieldNumber) {
  appvapiCollectRequest_FieldNumber_PlayVideo = 1,
  appvapiCollectRequest_FieldNumber_PlayVideoFulfill = 3,
  appvapiCollectRequest_FieldNumber_BrowseOtherHomepage = 4,
  appvapiCollectRequest_FieldNumber_ClickVideoTag = 5,
  appvapiCollectRequest_FieldNumber_LikeVideo = 6,
  appvapiCollectRequest_FieldNumber_CollectVideo = 8,
  appvapiCollectRequest_FieldNumber_ClickPostTag = 9,
  appvapiCollectRequest_FieldNumber_VisitHomepageForPost = 10,
  appvapiCollectRequest_FieldNumber_VisitHomepageForVideo = 11,
};

typedef GPB_ENUM(appvapiCollectRequest_BuriedPoint_OneOfCase) {
  appvapiCollectRequest_BuriedPoint_OneOfCase_GPBUnsetOneOfCase = 0,
  appvapiCollectRequest_BuriedPoint_OneOfCase_PlayVideo = 1,
  appvapiCollectRequest_BuriedPoint_OneOfCase_PlayVideoFulfill = 3,
  appvapiCollectRequest_BuriedPoint_OneOfCase_BrowseOtherHomepage = 4,
  appvapiCollectRequest_BuriedPoint_OneOfCase_ClickVideoTag = 5,
  appvapiCollectRequest_BuriedPoint_OneOfCase_LikeVideo = 6,
  appvapiCollectRequest_BuriedPoint_OneOfCase_CollectVideo = 8,
  appvapiCollectRequest_BuriedPoint_OneOfCase_ClickPostTag = 9,
  appvapiCollectRequest_BuriedPoint_OneOfCase_VisitHomepageForPost = 10,
  appvapiCollectRequest_BuriedPoint_OneOfCase_VisitHomepageForVideo = 11,
};

GPB_FINAL @interface appvapiCollectRequest : GPBMessage

@property(nonatomic, readonly) appvapiCollectRequest_BuriedPoint_OneOfCase buriedPointOneOfCase;

/** 播放视频 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiPlayVideo *playVideo;

/**
 * 播放视频 3妙
 *    PlayVideoThreeSeconds play_video_three_seconds = 2;
 * 播放视频 播完
 **/
@property(nonatomic, readwrite, strong, null_resettable) appvapiPlayVideoFulfill *playVideoFulfill;

/** 点击他人主页 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiBrowseOtherHomepage *browseOtherHomepage;

/** 点击视频标签 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiClickVideoTag *clickVideoTag;

/** 喜欢视频 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiLikeVideo *likeVideo;

/**
 * 下载视频
 *    DownloadVideo download_video = 7;
 * 收藏视频
 **/
@property(nonatomic, readwrite, strong, null_resettable) appvapiCollectVideo *collectVideo;

/** 点击帖子标签 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiClickPostTag *clickPostTag;

/** 从帖子内点击他人主页 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiVisitHomepageForPost *visitHomepageForPost;

/** 从视频内点击他人标签 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiVisitHomepageForVideo *visitHomepageForVideo;

@end

/**
 * Clears whatever value was set for the oneof 'buriedPoint'.
 **/
void appvapiCollectRequest_ClearBuriedPointOneOfCase(appvapiCollectRequest *message);

#pragma mark - appvapiPlayVideo

typedef GPB_ENUM(appvapiPlayVideo_FieldNumber) {
  appvapiPlayVideo_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiPlayVideo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

#pragma mark - appvapiPlayVideoThreeSeconds

typedef GPB_ENUM(appvapiPlayVideoThreeSeconds_FieldNumber) {
  appvapiPlayVideoThreeSeconds_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiPlayVideoThreeSeconds : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

#pragma mark - appvapiPlayVideoFulfill

typedef GPB_ENUM(appvapiPlayVideoFulfill_FieldNumber) {
  appvapiPlayVideoFulfill_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiPlayVideoFulfill : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

#pragma mark - appvapiBrowseOtherHomepage

typedef GPB_ENUM(appvapiBrowseOtherHomepage_FieldNumber) {
  appvapiBrowseOtherHomepage_FieldNumber_OtherUid = 1,
};

/**
 * 查看他人主页 从列表中点击
 **/
GPB_FINAL @interface appvapiBrowseOtherHomepage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *otherUid;
/** Test to see if @c otherUid has been set. */
@property(nonatomic, readwrite) BOOL hasOtherUid;

@end

#pragma mark - appvapiVisitHomepageForVideo

typedef GPB_ENUM(appvapiVisitHomepageForVideo_FieldNumber) {
  appvapiVisitHomepageForVideo_FieldNumber_Uid = 1,
  appvapiVisitHomepageForVideo_FieldNumber_VideoId = 2,
  appvapiVisitHomepageForVideo_FieldNumber_TagId = 3,
};

/**
 * 从视频中点击他人主页
 * 这个需要记录关系 某个视频标签-> 视频 -> 主页
 **/
GPB_FINAL @interface appvapiVisitHomepageForVideo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

/** 如果不是点击标签后点击的视频就不传这个 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *tagId;
/** Test to see if @c tagId has been set. */
@property(nonatomic, readwrite) BOOL hasTagId;

@end

#pragma mark - appvapiVisitHomepageForPost

typedef GPB_ENUM(appvapiVisitHomepageForPost_FieldNumber) {
  appvapiVisitHomepageForPost_FieldNumber_Uid = 1,
  appvapiVisitHomepageForPost_FieldNumber_PostId = 2,
  appvapiVisitHomepageForPost_FieldNumber_TagId = 3,
};

/**
 * 从帖子中点击他人主页
 * 这个需要记录关系 某个帖子标签-> 视频 -> 主页
 **/
GPB_FINAL @interface appvapiVisitHomepageForPost : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *uid;
/** Test to see if @c uid has been set. */
@property(nonatomic, readwrite) BOOL hasUid;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *postId;
/** Test to see if @c postId has been set. */
@property(nonatomic, readwrite) BOOL hasPostId;

/** 如果不是点击标签后点击的视频就不传这个 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *tagId;
/** Test to see if @c tagId has been set. */
@property(nonatomic, readwrite) BOOL hasTagId;

@end

#pragma mark - appvapiClickVideoTag

typedef GPB_ENUM(appvapiClickVideoTag_FieldNumber) {
  appvapiClickVideoTag_FieldNumber_VideoId = 1,
  appvapiClickVideoTag_FieldNumber_TagId = 2,
  appvapiClickVideoTag_FieldNumber_TagName = 3,
};

/**
 * 点击帖子标签
 **/
GPB_FINAL @interface appvapiClickVideoTag : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

/** 点击标签的id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *tagId;
/** Test to see if @c tagId has been set. */
@property(nonatomic, readwrite) BOOL hasTagId;

/** 点击的标签名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tagName;

@end

#pragma mark - appvapiClickPostTag

typedef GPB_ENUM(appvapiClickPostTag_FieldNumber) {
  appvapiClickPostTag_FieldNumber_PostId = 1,
  appvapiClickPostTag_FieldNumber_TagId = 2,
  appvapiClickPostTag_FieldNumber_TagName = 3,
};

/**
 * 点击帖子标签
 **/
GPB_FINAL @interface appvapiClickPostTag : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *postId;
/** Test to see if @c postId has been set. */
@property(nonatomic, readwrite) BOOL hasPostId;

/** 点击标签的id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *tagId;
/** Test to see if @c tagId has been set. */
@property(nonatomic, readwrite) BOOL hasTagId;

/** 点击的标签名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *tagName;

@end

#pragma mark - appvapiLikeVideo

typedef GPB_ENUM(appvapiLikeVideo_FieldNumber) {
  appvapiLikeVideo_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiLikeVideo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

#pragma mark - appvapiDownloadVideo

typedef GPB_ENUM(appvapiDownloadVideo_FieldNumber) {
  appvapiDownloadVideo_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiDownloadVideo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

#pragma mark - appvapiCollectVideo

typedef GPB_ENUM(appvapiCollectVideo_FieldNumber) {
  appvapiCollectVideo_FieldNumber_VideoId = 1,
};

GPB_FINAL @interface appvapiCollectVideo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *videoId;
/** Test to see if @c videoId has been set. */
@property(nonatomic, readwrite) BOOL hasVideoId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
