// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appv-primary-api-content-community.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class appvapiCommunityPost;
@class appvapiContentTag;
@class appvapiIdEncode;
@class appvapiMyCollectCommunityPosts;
@class appvapiMyStarCommunityPosts;
@class appvapiPublishingCommunityPostMedia;
@class appvapiPublishingPost;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - appvapiAppvPrimaryApiContentCommunityRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface appvapiAppvPrimaryApiContentCommunityRoot : GPBRootObject
@end

#pragma mark - appvapiPublishingCommunityPostMediaRequest

typedef GPB_ENUM(appvapiPublishingCommunityPostMediaRequest_FieldNumber) {
  appvapiPublishingCommunityPostMediaRequest_FieldNumber_Content = 1,
  appvapiPublishingCommunityPostMediaRequest_FieldNumber_PublishingCommunityPostMedia = 2,
  appvapiPublishingCommunityPostMediaRequest_FieldNumber_TagsArray = 3,
  appvapiPublishingCommunityPostMediaRequest_FieldNumber_TagIdsArray = 4,
};

GPB_FINAL @interface appvapiPublishingCommunityPostMediaRequest : GPBMessage

/** 帖子文本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 帖子资源 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiPublishingCommunityPostMedia *publishingCommunityPostMedia;
/** Test to see if @c publishingCommunityPostMedia has been set. */
@property(nonatomic, readwrite) BOOL hasPublishingCommunityPostMedia;

/** 标签 20220303后，该字段废弃，使用 tag_ids 字段。客户端不需要传递完整的标签信息，只需要传递标签id即可。 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiContentTag*> *tagsArray GPB_DEPRECATED_MSG("appvapi.PublishingCommunityPostMediaRequest.tags is deprecated (see appv-primary-api-content-community.proto).");
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count GPB_DEPRECATED_MSG("appvapi.PublishingCommunityPostMediaRequest.tags is deprecated (see appv-primary-api-content-community.proto).");

/** 标签id列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiIdEncode*> *tagIdsArray;
/** The number of items in @c tagIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagIdsArray_Count;

@end

#pragma mark - appvapiPublishingCommunityPostContentRequest

typedef GPB_ENUM(appvapiPublishingCommunityPostContentRequest_FieldNumber) {
  appvapiPublishingCommunityPostContentRequest_FieldNumber_Content = 1,
  appvapiPublishingCommunityPostContentRequest_FieldNumber_TagsArray = 2,
  appvapiPublishingCommunityPostContentRequest_FieldNumber_TagIdsArray = 3,
};

GPB_FINAL @interface appvapiPublishingCommunityPostContentRequest : GPBMessage

/** 帖子文本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 标签 20220303后，该字段废弃，使用 tag_ids 字段。客户端不需要传递完整的标签信息，只需要传递标签id即可。 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiContentTag*> *tagsArray GPB_DEPRECATED_MSG("appvapi.PublishingCommunityPostContentRequest.tags is deprecated (see appv-primary-api-content-community.proto).");
/** The number of items in @c tagsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagsArray_Count GPB_DEPRECATED_MSG("appvapi.PublishingCommunityPostContentRequest.tags is deprecated (see appv-primary-api-content-community.proto).");

/** 标签id列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiIdEncode*> *tagIdsArray;
/** The number of items in @c tagIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagIdsArray_Count;

@end

#pragma mark - appvapiListCommunityPostsResponse

typedef GPB_ENUM(appvapiListCommunityPostsResponse_FieldNumber) {
  appvapiListCommunityPostsResponse_FieldNumber_CommunityPostsArray = 1,
  appvapiListCommunityPostsResponse_FieldNumber_PublishingPost = 2,
};

GPB_FINAL @interface appvapiListCommunityPostsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiCommunityPost*> *communityPostsArray;
/** The number of items in @c communityPostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger communityPostsArray_Count;

/** 该字段针对我的发布接口添加的字段 */
@property(nonatomic, readwrite, strong, null_resettable) appvapiPublishingPost *publishingPost;
/** Test to see if @c publishingPost has been set. */
@property(nonatomic, readwrite) BOOL hasPublishingPost;

@end

#pragma mark - appvapiPublishingPost

typedef GPB_ENUM(appvapiPublishingPost_FieldNumber) {
  appvapiPublishingPost_FieldNumber_PublishingCount = 1,
};

GPB_FINAL @interface appvapiPublishingPost : GPBMessage

@property(nonatomic, readwrite) uint32_t publishingCount;

@end

#pragma mark - appvapiListCommunityPostsRequest

typedef GPB_ENUM(appvapiListCommunityPostsRequest_FieldNumber) {
  appvapiListCommunityPostsRequest_FieldNumber_LastId = 1,
};

GPB_FINAL @interface appvapiListCommunityPostsRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *lastId;
/** Test to see if @c lastId has been set. */
@property(nonatomic, readwrite) BOOL hasLastId;

@end

#pragma mark - appvapiListSearchCommunityPostsRequest

typedef GPB_ENUM(appvapiListSearchCommunityPostsRequest_FieldNumber) {
  appvapiListSearchCommunityPostsRequest_FieldNumber_Content = 1,
  appvapiListSearchCommunityPostsRequest_FieldNumber_Current = 2,
};

GPB_FINAL @interface appvapiListSearchCommunityPostsRequest : GPBMessage

/** 搜索的文本内容(标签或帖子内容) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 页码 */
@property(nonatomic, readwrite) uint32_t current;

@end

#pragma mark - appvapiListTagCommunityPostsRequest

typedef GPB_ENUM(appvapiListTagCommunityPostsRequest_FieldNumber) {
  appvapiListTagCommunityPostsRequest_FieldNumber_TagId = 1,
  appvapiListTagCommunityPostsRequest_FieldNumber_Offset = 2,
};

GPB_FINAL @interface appvapiListTagCommunityPostsRequest : GPBMessage

/** 标签id */
@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *tagId;
/** Test to see if @c tagId has been set. */
@property(nonatomic, readwrite) BOOL hasTagId;

/** 当前页码 */
@property(nonatomic, readwrite) uint32_t offset;

@end

#pragma mark - appvapiDeleteCommunityPostRequest

typedef GPB_ENUM(appvapiDeleteCommunityPostRequest_FieldNumber) {
  appvapiDeleteCommunityPostRequest_FieldNumber_PostIdsArray = 1,
};

GPB_FINAL @interface appvapiDeleteCommunityPostRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiIdEncode*> *postIdsArray;
/** The number of items in @c postIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postIdsArray_Count;

@end

#pragma mark - appvapiDeleteCommunityPostResponse

typedef GPB_ENUM(appvapiDeleteCommunityPostResponse_FieldNumber) {
  appvapiDeleteCommunityPostResponse_FieldNumber_PostIdsArray = 1,
};

GPB_FINAL @interface appvapiDeleteCommunityPostResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiIdEncode*> *postIdsArray;
/** The number of items in @c postIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postIdsArray_Count;

@end

#pragma mark - appvapiListMyStarCommunityPostsResponse

typedef GPB_ENUM(appvapiListMyStarCommunityPostsResponse_FieldNumber) {
  appvapiListMyStarCommunityPostsResponse_FieldNumber_MyStarCommunityPostsArray = 1,
};

GPB_FINAL @interface appvapiListMyStarCommunityPostsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiMyStarCommunityPosts*> *myStarCommunityPostsArray;
/** The number of items in @c myStarCommunityPostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger myStarCommunityPostsArray_Count;

@end

#pragma mark - appvapiListMyCollectCommunityPostsResponse

typedef GPB_ENUM(appvapiListMyCollectCommunityPostsResponse_FieldNumber) {
  appvapiListMyCollectCommunityPostsResponse_FieldNumber_MyCollectCommunityPostsArray = 1,
};

GPB_FINAL @interface appvapiListMyCollectCommunityPostsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<appvapiMyCollectCommunityPosts*> *myCollectCommunityPostsArray;
/** The number of items in @c myCollectCommunityPostsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger myCollectCommunityPostsArray_Count;

@end

#pragma mark - appvapiMyStarCommunityPosts

typedef GPB_ENUM(appvapiMyStarCommunityPosts_FieldNumber) {
  appvapiMyStarCommunityPosts_FieldNumber_CommunityPosts = 1,
  appvapiMyStarCommunityPosts_FieldNumber_LikeId = 2,
};

GPB_FINAL @interface appvapiMyStarCommunityPosts : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiCommunityPost *communityPosts;
/** Test to see if @c communityPosts has been set. */
@property(nonatomic, readwrite) BOOL hasCommunityPosts;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *likeId;
/** Test to see if @c likeId has been set. */
@property(nonatomic, readwrite) BOOL hasLikeId;

@end

#pragma mark - appvapiMyCollectCommunityPosts

typedef GPB_ENUM(appvapiMyCollectCommunityPosts_FieldNumber) {
  appvapiMyCollectCommunityPosts_FieldNumber_CommunityPosts = 1,
  appvapiMyCollectCommunityPosts_FieldNumber_CollectionId = 2,
};

GPB_FINAL @interface appvapiMyCollectCommunityPosts : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) appvapiCommunityPost *communityPosts;
/** Test to see if @c communityPosts has been set. */
@property(nonatomic, readwrite) BOOL hasCommunityPosts;

@property(nonatomic, readwrite, strong, null_resettable) appvapiIdEncode *collectionId;
/** Test to see if @c collectionId has been set. */
@property(nonatomic, readwrite) BOOL hasCollectionId;

@end

#pragma mark - appvapiListRecommendCommunityPostsRequest

typedef GPB_ENUM(appvapiListRecommendCommunityPostsRequest_FieldNumber) {
  appvapiListRecommendCommunityPostsRequest_FieldNumber_Offset = 1,
};

GPB_FINAL @interface appvapiListRecommendCommunityPostsRequest : GPBMessage

@property(nonatomic, readwrite) uint32_t offset;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
