// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange-primary-api-announcement.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class serviceexchangeAnnouncementMsg;
@class utilidentitysdkIdEncode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - serviceexchangeExchangePrimaryApiAnnouncementRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface serviceexchangeExchangePrimaryApiAnnouncementRoot : GPBRootObject
@end

#pragma mark - serviceexchangeListAnnouncementRequest

typedef GPB_ENUM(serviceexchangeListAnnouncementRequest_FieldNumber) {
  serviceexchangeListAnnouncementRequest_FieldNumber_LastMsgId = 1,
};

/**
 * 拉取公告请求参数
 **/
GPB_FINAL @interface serviceexchangeListAnnouncementRequest : GPBMessage

/** 客户端本地的最大消息版本id。如果没有则不传，则会返回最新的10条公告信息 */
@property(nonatomic, readwrite, strong, null_resettable) utilidentitysdkIdEncode *lastMsgId;
/** Test to see if @c lastMsgId has been set. */
@property(nonatomic, readwrite) BOOL hasLastMsgId;

@end

#pragma mark - serviceexchangeListAnnouncementResponse

typedef GPB_ENUM(serviceexchangeListAnnouncementResponse_FieldNumber) {
  serviceexchangeListAnnouncementResponse_FieldNumber_AnnouncementMsgsArray = 1,
  serviceexchangeListAnnouncementResponse_FieldNumber_HasNext = 2,
};

/**
 * 拉取公告响应参数
 **/
GPB_FINAL @interface serviceexchangeListAnnouncementResponse : GPBMessage

/** 消息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<serviceexchangeAnnouncementMsg*> *announcementMsgsArray;
/** The number of items in @c announcementMsgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger announcementMsgsArray_Count;

/** 是否包含下一页 */
@property(nonatomic, readwrite) BOOL hasNext;

@end

#pragma mark - serviceexchangeAnnouncementMsg

typedef GPB_ENUM(serviceexchangeAnnouncementMsg_FieldNumber) {
  serviceexchangeAnnouncementMsg_FieldNumber_MsgId = 1,
  serviceexchangeAnnouncementMsg_FieldNumber_Title = 2,
  serviceexchangeAnnouncementMsg_FieldNumber_Content = 3,
  serviceexchangeAnnouncementMsg_FieldNumber_SendTime = 4,
};

/**
 * 系统公告消息
 **/
GPB_FINAL @interface serviceexchangeAnnouncementMsg : GPBMessage

/** 消息版本id（保证有序递增） */
@property(nonatomic, readwrite, strong, null_resettable) utilidentitysdkIdEncode *msgId;
/** Test to see if @c msgId has been set. */
@property(nonatomic, readwrite) BOOL hasMsgId;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 发送时间 */
@property(nonatomic, readwrite) uint64_t sendTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
