// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uc-primary-api-sign.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class serviceucBindAccounts;
@class serviceucDeviceInfo;
@class serviceucSmsValid;
@class serviceucTelephone;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum serviceucOSName

typedef GPB_ENUM(serviceucOSName) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  serviceucOSName_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  serviceucOSName_OsNameIos = 0,
  serviceucOSName_OsNameAndroid = 1,
};

GPBEnumDescriptor *serviceucOSName_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL serviceucOSName_IsValidValue(int32_t value);

#pragma mark - serviceucUcPrimaryApiSignRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface serviceucUcPrimaryApiSignRoot : GPBRootObject
@end

#pragma mark - serviceucSignInGmRequest

typedef GPB_ENUM(serviceucSignInGmRequest_FieldNumber) {
  serviceucSignInGmRequest_FieldNumber_Uid = 1,
};

GPB_FINAL @interface serviceucSignInGmRequest : GPBMessage

/** 要登陆的 gm uid */
@property(nonatomic, readwrite) uint64_t uid;

@end

#pragma mark - serviceucJwtTokenResponse

typedef GPB_ENUM(serviceucJwtTokenResponse_FieldNumber) {
  serviceucJwtTokenResponse_FieldNumber_JwtToken = 1,
};

GPB_FINAL @interface serviceucJwtTokenResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *jwtToken;

@end

#pragma mark - serviceucTokenRequest

GPB_FINAL @interface serviceucTokenRequest : GPBMessage

@end

#pragma mark - serviceucGuestRequest

typedef GPB_ENUM(serviceucGuestRequest_FieldNumber) {
  serviceucGuestRequest_FieldNumber_Uuid = 1,
  serviceucGuestRequest_FieldNumber_ShareCode = 2,
  serviceucGuestRequest_FieldNumber_DeviceInfo = 3,
};

GPB_FINAL @interface serviceucGuestRequest : GPBMessage

/**
 * 设备 uuid 客户端 逻辑 :
 * 查询 uuid 存储 存在值传入值 不存在则传入空
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 分享码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *shareCode;

/** 设备信息 */
@property(nonatomic, readwrite, strong, null_resettable) serviceucDeviceInfo *deviceInfo;
/** Test to see if @c deviceInfo has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceInfo;

@end

#pragma mark - serviceucTelephoneSignInRequest

typedef GPB_ENUM(serviceucTelephoneSignInRequest_FieldNumber) {
  serviceucTelephoneSignInRequest_FieldNumber_Sms = 1,
  serviceucTelephoneSignInRequest_FieldNumber_Tel = 2,
  serviceucTelephoneSignInRequest_FieldNumber_Uuid = 3,
  serviceucTelephoneSignInRequest_FieldNumber_DeviceInfo = 4,
};

GPB_FINAL @interface serviceucTelephoneSignInRequest : GPBMessage

/** 短信验证码 Id */
@property(nonatomic, readwrite, strong, null_resettable) serviceucSmsValid *sms;
/** Test to see if @c sms has been set. */
@property(nonatomic, readwrite) BOOL hasSms;

/** 手机号 */
@property(nonatomic, readwrite, strong, null_resettable) serviceucTelephone *tel;
/** Test to see if @c tel has been set. */
@property(nonatomic, readwrite) BOOL hasTel;

/**
 * 设备 id 客户端登陆时传入，后端会自动切换用户的设备
 * 查询 uuid 存储 存在值传入值 不存在则传入空
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 设备信息 */
@property(nonatomic, readwrite, strong, null_resettable) serviceucDeviceInfo *deviceInfo;
/** Test to see if @c deviceInfo has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceInfo;

@end

#pragma mark - serviceucAccountAccessResponse

typedef GPB_ENUM(serviceucAccountAccessResponse_FieldNumber) {
  serviceucAccountAccessResponse_FieldNumber_UcToken = 1,
  serviceucAccountAccessResponse_FieldNumber_Bind = 2,
  serviceucAccountAccessResponse_FieldNumber_Uuid = 3,
};

GPB_FINAL @interface serviceucAccountAccessResponse : GPBMessage

/** 用于请求 uc 等服务的 token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ucToken;

/** 已经绑定的账户 */
@property(nonatomic, readwrite, strong, null_resettable) serviceucBindAccounts *bind;
/** Test to see if @c bind has been set. */
@property(nonatomic, readwrite) BOOL hasBind;

/** 针对新设备服务端生成的uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@end

#pragma mark - serviceucSignOutRequest

GPB_FINAL @interface serviceucSignOutRequest : GPBMessage

@end

#pragma mark - serviceucSignOutResponse

GPB_FINAL @interface serviceucSignOutResponse : GPBMessage

@end

#pragma mark - serviceucDeviceInfo

typedef GPB_ENUM(serviceucDeviceInfo_FieldNumber) {
  serviceucDeviceInfo_FieldNumber_Uuid = 1,
  serviceucDeviceInfo_FieldNumber_AndroidId = 2,
  serviceucDeviceInfo_FieldNumber_Brand = 3,
  serviceucDeviceInfo_FieldNumber_Idfa = 4,
  serviceucDeviceInfo_FieldNumber_Imei = 5,
  serviceucDeviceInfo_FieldNumber_Model = 6,
  serviceucDeviceInfo_FieldNumber_OsName = 7,
  serviceucDeviceInfo_FieldNumber_OsVersion = 8,
};

/**
 * 设备信息
 **/
GPB_FINAL @interface serviceucDeviceInfo : GPBMessage

/** ios uuid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 安卓 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *androidId;

/** 设备品牌 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

/** 广告标示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *idfa;

/** 设备串号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imei;

/** 设备型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** 操作系统名称 */
@property(nonatomic, readwrite) serviceucOSName osName;

/** 操作系统版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

@end

/**
 * Fetches the raw value of a @c serviceucDeviceInfo's @c osName property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t serviceucDeviceInfo_OsName_RawValue(serviceucDeviceInfo *message);
/**
 * Sets the raw value of an @c serviceucDeviceInfo's @c osName property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetserviceucDeviceInfo_OsName_RawValue(serviceucDeviceInfo *message, int32_t value);

#pragma mark - serviceucBindAccounts

typedef GPB_ENUM(serviceucBindAccounts_FieldNumber) {
  serviceucBindAccounts_FieldNumber_Uuid = 1,
  serviceucBindAccounts_FieldNumber_Tel = 2,
};

GPB_FINAL @interface serviceucBindAccounts : GPBMessage

/** 游客账户 肯定存在 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 绑定的账号, 手机号绑定了, 就会有数据 */
@property(nonatomic, readwrite, strong, null_resettable) serviceucTelephone *tel;
/** Test to see if @c tel has been set. */
@property(nonatomic, readwrite) BOOL hasTel;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
