// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util-basic.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class utilpbdatametadataDataIdvFiled;
@class utilpbdatametadataDataKvFiled;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - utilpbdatametadataUtilBasicRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface utilpbdatametadataUtilBasicRoot : GPBRootObject
@end

#pragma mark - utilpbdatametadataIdUint64

typedef GPB_ENUM(utilpbdatametadataIdUint64_FieldNumber) {
  utilpbdatametadataIdUint64_FieldNumber_Id_p = 1,
};

/**
 * 一些通用的 entity
 * 根据主键ID发起请求
 **/
GPB_FINAL @interface utilpbdatametadataIdUint64 : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@end

#pragma mark - utilpbdatametadataAppendIdUint64

typedef GPB_ENUM(utilpbdatametadataAppendIdUint64_FieldNumber) {
  utilpbdatametadataAppendIdUint64_FieldNumber_LastId = 1,
};

/**
 * 一些通用的 entity
 **/
GPB_FINAL @interface utilpbdatametadataAppendIdUint64 : GPBMessage

/**
 * 此参数为追加分页时使用
 * 每次 排序返回的 内容 ID 的最后一个值
 **/
@property(nonatomic, readwrite) uint64_t lastId;

@end

#pragma mark - utilpbdatametadataStrWithClean

typedef GPB_ENUM(utilpbdatametadataStrWithClean_FieldNumber) {
  utilpbdatametadataStrWithClean_FieldNumber_Raw = 1,
  utilpbdatametadataStrWithClean_FieldNumber_IsClean = 2,
};

/**
 * 需要清除的 str 结构
 **/
GPB_FINAL @interface utilpbdatametadataStrWithClean : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *raw;

/** 是否需要 clean 字段 */
@property(nonatomic, readwrite) BOOL isClean;

@end

#pragma mark - utilpbdatametadataDataKvs

typedef GPB_ENUM(utilpbdatametadataDataKvs_FieldNumber) {
  utilpbdatametadataDataKvs_FieldNumber_KvsArray = 1,
};

/**
 * 常见的  id -> value
 **/
GPB_FINAL @interface utilpbdatametadataDataKvs : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<utilpbdatametadataDataKvFiled*> *kvsArray;
/** The number of items in @c kvsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvsArray_Count;

@end

#pragma mark - utilpbdatametadataDataIdVs

typedef GPB_ENUM(utilpbdatametadataDataIdVs_FieldNumber) {
  utilpbdatametadataDataIdVs_FieldNumber_IdVsArray = 1,
};

GPB_FINAL @interface utilpbdatametadataDataIdVs : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<utilpbdatametadataDataIdvFiled*> *idVsArray;
/** The number of items in @c idVsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger idVsArray_Count;

@end

#pragma mark - utilpbdatametadataDataIdvFiled

typedef GPB_ENUM(utilpbdatametadataDataIdvFiled_FieldNumber) {
  utilpbdatametadataDataIdvFiled_FieldNumber_Id_p = 1,
  utilpbdatametadataDataIdvFiled_FieldNumber_IdValue = 2,
};

GPB_FINAL @interface utilpbdatametadataDataIdvFiled : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *idValue;

@end

#pragma mark - utilpbdatametadataDataKvFiled

typedef GPB_ENUM(utilpbdatametadataDataKvFiled_FieldNumber) {
  utilpbdatametadataDataKvFiled_FieldNumber_KvKey = 1,
  utilpbdatametadataDataKvFiled_FieldNumber_KvValue = 2,
};

GPB_FINAL @interface utilpbdatametadataDataKvFiled : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *kvKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *kvValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
